version: "3.9"

services:
  web:
    build: .
    container_name: paymentgateway_be-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=paymentgateway_be.settings
    command: gunicorn paymentgateway_be.wsgi:application --bind 0.0.0.0:8000

